# Generated by Django 5.1.7 on 2025-03-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Machine', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('organization', models.TextField(choices=[('VEZARAT_SAMT', 'وزارت صنعت معدن و تجارت'), ('VEZARAT_JAHAD', 'وزارت جهاد کشاورزی')])),
                ('coowner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='union', to='User.coowneruser')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine.machine')),
            ],
        ),
    ]
