# Generated by Django 5.1.7 on 2025-03-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_initial'),
        ('Union', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='machines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine'),
        ),
    ]
