# Generated by Django 5.1.7 on 2025-03-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0002_alter_union_machines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='machines',
        ),
    ]
