# Generated by Django 5.1.7 on 2025-03-16 07:32

import User.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0003_remove_union_machines'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='union',
            managers=[
                ('objects', User.managers.CustomUserManager()),
            ],
        ),
    ]
