# Generated by Django 5.1.7 on 2025-03-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_number', models.IntegerField()),
                ('engine_number', models.IntegerField()),
                ('chassis_number', models.IntegerField()),
                ('cylinder_count', models.IntegerField()),
                ('number_plate', models.TextField()),
                ('general_type', models.TextField(choices=[('RAHSAZI', 'راه سازی'), ('KESHAVARZI', 'کشاورزی')])),
                ('general_sub_type', models.TextField(choices=[('LOADER', 'لودر'), ('BILMECHANIKI', 'بیل مکانیکی'), ('BOLDOUZER', 'بلدوزر'), ('GRADER', 'گریدر'), ('BOBCAT', 'باب کت'), ('TRACTOR', 'تراکتور')])),
                ('model', models.TextField(choices=[('LOADER950', '950 لودر')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='User.machineowner')),
            ],
        ),
    ]
