# Generated by Django 5.1.7 on 2025-03-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Machine', '0001_initial'),
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='User.machineowner'),
        ),
    ]
