# Generated by Django 5.1.7 on 2025-03-12 12:36

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.TextField()),
                ('representative_name', models.TextField()),
                ('national_id', models.TextField(unique=True)),
                ('economy_number', models.TextField()),
                ('registered_number', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('User.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RealUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('certificate_id', models.TextField()),
                ('national_code', models.TextField(unique=True)),
                ('father_name', models.TextField()),
                ('birth_date', models.DateField()),
                ('phone_number', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('User.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
