# Generated by Django 5.1.7 on 2025-03-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DigitalSign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('certificate_id', models.IntegerField()),
                ('national_code', models.IntegerField()),
                ('father_name', models.TextField()),
                ('birth_date', models.DateField()),
                ('phone_number', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('company_name', models.TextField()),
                ('representative_name', models.TextField()),
                ('national_id', models.IntegerField()),
                ('economy_number', models.IntegerField()),
                ('registered_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineOwner',
            fields=[
                ('realuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.realuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('User.realuser',),
        ),
        migrations.CreateModel(
            name='CoownerUser',
            fields=[
                ('realuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.realuser')),
                ('digital_sign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='DigitalSign.digitalsign')),
            ],
            options={
                'abstract': False,
            },
            bases=('User.realuser',),
        ),
    ]
