# Generated by Django 5.1.7 on 2025-03-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('certificate_id', models.IntegerField()),
                ('national_code', models.IntegerField()),
                ('father_name', models.TextField()),
                ('birth_date', models.DateField()),
                ('phone_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PassAuthUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('password', models.TextField()),
            ],
            bases=('User.user',),
        ),
    ]
