# Generated by Django 5.1.7 on 2025-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaluser',
            name='economy_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='national_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='registered_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='realuser',
            name='certificate_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='realuser',
            name='national_code',
            field=models.TextField(),
        ),
    ]
