# Generated by Django 5.1.7 on 2025-03-12 11:10

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DigitalSign', '0001_initial'),
        ('Union', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='union_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Union.union'),
        ),
        migrations.CreateModel(
            name='MachineOwner',
            fields=[
                ('realuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.realuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('User.realuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoownerUser',
            fields=[
                ('realuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.realuser')),
                ('digital_sign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='DigitalSign.digitalsign')),
            ],
            options={
                'abstract': False,
            },
            bases=('User.realuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
