# Generated by Django 5.1.7 on 2025-03-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalSign', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
            ],
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='CoownerUser',
            fields=[
                ('passauthuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.passauthuser')),
                ('digital_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalSign.digitalsign')),
            ],
            bases=('User.passauthuser',),
        ),
    ]
