# Generated by Django 5.1.7 on 2025-03-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0001_initial'),
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='union_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Union.union'),
        ),
    ]
