# Generated by Django 5.1.7 on 2025-03-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaluser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='realuser',
            name='user',
        ),
    ]
