# Generated by Django 5.1.7 on 2025-03-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_union', 'Whether this account is for a union or not')]},
        ),
    ]
