# Generated by Django 5.1.7 on 2025-03-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessLicense', '0003_alter_businesslicenseimage_owner'),
        ('Machine', '0003_alter_machine_owner'),
        ('User', '0005_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineOwner',
        ),
    ]
