# Generated by Django 5.1.7 on 2025-03-16 07:32

import User.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_machineowner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coowneruser',
            managers=[
                ('objects', User.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='legaluser',
            managers=[
                ('objects', User.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='realuser',
            managers=[
                ('objects', User.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', User.managers.CustomUserManager()),
            ],
        ),
    ]
